export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

//COMPANY'S ACTIONS
export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS';


//STUDENT'S ACTIONS
export const LOAD_STUDENTS_SUCCESS = 'LOAD_STUDENTS_SUCCESS';
export const ON_APPLY = 'ON_APPLY';

//TUTOR'S ACTIONS
export const LOAD_TUTORS_SUCCESS = 'LOAD_TUTORS_SUCCESS';



