
const StudentAPI = {
    players: [
      { number: 1, 
        name: "Kevin Pansawira",  
        school: "UCSD", 
        GPA: "3.99", 
        year:"2018", 
        pic:"./kpan.jpg",
        major: "Computer Science", 
        status: "",
        applications: [], 
        username: "kp", 
        password: "kp12345", 
        intern: "", 
        mailing: []
      },
      { number: 2, 
        name: "Dave Defender", 
        school: "MIT", 
        GPA: "3.99", 
        year:"2019", 
        pic:"./pp1.jpeg",
        major: "Computer Science", 
        status: "",
        applications: [], 
        username: "dd", 
        password: "kp12345", 
        intern: "", 
        mailing: []
      },
      { number: 3, name: "Sam Sweeper",
       school: "UCB",
        GPA: "3.99", 
        year:"2019",
         pic:"./pp1.jpeg",
         major: "Computer Science", 
         status: "",
         applications: [], 
         username: "ss", 
         password: "kp12345", 
         intern: "", 
         mailing: []
        },
      { number: 4,
         name: "Matt Midfielder", 
         school: "UCSD", 
         GPA: "3.99", 
         year:"2019", 
         pic:"./pp1.jpeg",
         major: "Computer Science", 
         status: "",
         applications: [], 
         username: "mm", 
         password: "kp12345", 
         intern: "", 
         mailing: []},
      { number: 5,
        name: "William Winger", 
        school: "UCSD",
        GPA: "3.99",
        year:"2019", 
        pic:"./pp1.jpeg",
        major: "Computer Science", 
        status: "",
        applications: [], 
        username: "ww", 
        password: "kp12345", 
        intern: "", 
        mailing: []},
      { number: 6, 
        name: "Fillipe Forward", 
        school: "UCSD", 
        GPA: "3.99", 
        year:"2019", 
        pic:"./pp1.jpeg",
        major: "Computer Science", 
        status: "",
        applications: [], 
        username: "ff", 
        password: "kp12345", 
        intern: "", 
        mailing: []}
    ],
    all: function() { return this.players},
    get: function(id) {
      const isPlayer = p => p.number === id
      return this.players.find(isPlayer)
    }
  }
  
  export default StudentAPI  